# PrimeAIExplorer v0.2.1 - canonical dataset workflow

cd C:\PrimeAIExplorer\release\PrimeAIExplorer_v0_2_1

Set-ExecutionPolicy -Scope Process -ExecutionPolicy Bypass
.\install.ps1
.\run_tests.ps1
.\run_demo.ps1

# Locate the canonical cases.csv generated by EXP-000001.
Get-ChildItem C:\PrimeAIExplorer\experiments\exp000001 -Recurse -File -Filter cases.csv |
    Select-Object FullName, Length, LastWriteTime

# Set this to the path returned above.
$Dataset = "C:\PrimeAIExplorer\experiments\exp000001\dataset\cases.csv"

.\.venv\Scripts\paiexp.exe dataset-check `
    --dataset $Dataset

.\.venv\Scripts\paiexp.exe analyze `
    --responses C:\PrimeAIExplorer\experiments\exp000001\pilot_001 `
    --dataset $Dataset `
    --output C:\PrimeAIExplorer\experiments\exp000001\analysis_v021\pilot_001 `
    --model GPT-5.6-Thinking `
    --experiment-id EXP-000001 `
    --pilot-id pilot_001

.\.venv\Scripts\paiexp.exe verify `
    --analysis C:\PrimeAIExplorer\experiments\exp000001\analysis_v021\pilot_001

Start-Process C:\PrimeAIExplorer\experiments\exp000001\analysis_v021\pilot_001\report.html
